from __future__ import annotations

import os
from typing import Annotated, Any

import requests
from semantic_kernel.functions import kernel_function


class JiraSlackBridgePlugin:
    def __init__(self) -> None:
        self.base_url = os.getenv("ORCHESTRATION_BRIDGE_URL", "http://localhost:3010")
        self.api_key = os.getenv("ORCHESTRATION_API_KEY", "")
        self.default_slack_channel = os.getenv("DEFAULT_SLACK_CHANNEL", "")

    def _default_ticket_description(self, summary: str) -> str:
        return (
            "Auto-generated by the orchestration layer.\n\n"
            f"Requested ticket summary: {summary}"
        )

    def _headers(self) -> dict[str, str]:
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["x-api-key"] = self.api_key
        return headers

    def _post_json(self, path: str, payload: dict[str, Any]) -> str:
        response = requests.post(
            f"{self.base_url}{path}",
            json=payload,
            headers=self._headers(),
            timeout=30,
        )
        if not response.ok:
            body = response.text.strip()
            raise requests.HTTPError(
                f"{response.status_code} {response.reason} for {path}. "
                f"Bridge response: {body or 'empty body'}"
            )
        return response.text

    @kernel_function(
        name="create_jira_ticket",
        description="Create a Jira ticket and optionally notify Slack using the Node bridge."
    )
    def create_jira_ticket(
        self,
        summary: Annotated[str, "A short Jira ticket summary."],
        description: Annotated[
            str,
            "A detailed Jira ticket description. Leave empty to auto-generate a default description."
        ] = "",
        issue_type: Annotated[str, "Jira issue type like Task or Bug."] = "Task",
        project_key: Annotated[str, "Jira project key. Leave empty to use the default project."] = "",
        notify_slack: Annotated[bool, "Whether Slack should be notified after Jira is created."] = True,
        slack_channel: Annotated[str, "Slack channel override. Leave empty to use the default channel."] = "",
        slack_message: Annotated[str, "Custom Slack message. Leave empty to let the server build it."] = ""
    ) -> str:
        resolved_description = description.strip() or self._default_ticket_description(summary)

        payload = {
            "summary": summary,
            "description": resolved_description,
            "issueType": issue_type,
            "projectKey": project_key or None,
            "notifySlack": notify_slack,
            "slackChannel": slack_channel or None,
            "slackMessage": slack_message or None,
        }

        return self._post_json("/actions/create-jira-ticket", payload)

    @kernel_function(
        name="send_slack_message",
        description="Send a Slack message through the Node bridge."
    )
    def send_slack_message(
        self,
        text: Annotated[str, "Message text to send to Slack."],
        channel: Annotated[str, "Slack channel name or ID. Leave empty to use the default channel."] = "",
    ) -> str:
        resolved_channel = channel or self.default_slack_channel
        return self._post_json(
            "/actions/send-slack-message",
            {"channel": resolved_channel, "text": text},
        )

    @kernel_function(
        name="update_jira_status",
        description="Update Jira issue status (transition) and optionally notify Slack using the Node bridge."
    )
    def update_jira_status(
        self,
        issue_identifier: Annotated[
            str,
            "Jira issue key (e.g., SCRUM-123) or a unique issue summary/title."
        ],
        target_status: Annotated[str, "Target Jira workflow status (e.g., In Progress, Done)."],
        project_key: Annotated[str, "Jira project key. Leave empty to use the default project."] = "",
        notify_slack: Annotated[bool, "Whether Slack should be notified after status update."] = True,
        slack_channel: Annotated[str, "Slack channel override. Leave empty to use the default channel."] = "",
        slack_message: Annotated[str, "Custom Slack message. Leave empty to let the server build it."] = ""
    ) -> str:
        payload = {
            "issueIdentifier": issue_identifier,
            "targetStatus": target_status,
            "projectKey": project_key or None,
            "notifySlack": notify_slack,
            "slackChannel": slack_channel or None,
            "slackMessage": slack_message or None,
        }

        return self._post_json("/actions/update-jira-status", payload)

    @kernel_function(
        name="get_execution_policy",
        description="Return orchestration policy and operating rules for Jira and Slack execution."
    )
    def get_execution_policy(self) -> dict[str, Any]:
        return {
            "rules": [
                "Always create a Jira ticket before posting a Slack status about that ticket.",
                "If the Jira summary is present but description is missing, auto-generate a default description.",
                "Ask a follow-up only when the action truly cannot proceed with configured defaults.",
                "Use Task as the default issue type unless the user clearly indicates Bug or Incident behavior.",
                "Use the configured default Jira project and Slack channel unless the user specifies overrides.",
            ]
        }
